version: '2'
services:
    php:
        build: ./php-fpm
        volumes:
            - ./:/var/www/trivago-task
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - percona
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www/trivago-task
            - ./nginx/trivago-task.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    percona:
        image: percona/percona-server:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "symf0ny"
        ports:
            - "3333:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8899:80
        links:
            - percona
        environment:
            MYSQL_USERNAME: "root"
            MYSQL_ROOT_PASSWORD: "symf0ny"
            PMA_HOST: percona